name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            arch: x64
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install Dependencies
        run: npm install

      - name: Get version and name from package.json
        id: get_version_name
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
          echo "::set-output name=name::$(node -p "require('./package.json').name")"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version_name.outputs.version }}
          release_name: Release ${{ steps.get_version_name.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron App
        run: npm run dist -- --x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
